# Generated by Django 4.2.6 on 2023-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_spamforallusers_send_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamforallusers',
            name='only_admin',
            field=models.BooleanField(default=False),
        ),
    ]
