version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  celery_worker:
    build: .
    command: celery -A VetrofPerScoolProject worker --loglevel=info
    volumes:
      - .:/code

  celery_beat:
    build: .
    command: celery -A VetrofPerScoolProject beat -l info
    volumes:
      - .:/code

  redis:
    image: redis
    ports:
      - "6379:6379"

  flower:
    image: mher/flower:0.9.5
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5555:5555