# Generated by Django 4.2.6 on 2023-12-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgspam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tg_spam_image'),
        ),
    ]
