# Generated by Django 4.2.6 on 2023-11-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0002_alter_telegramuser_user_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
