# Generated by Django 4.2.6 on 2023-12-01 08:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0005_tgspam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgspam',
            name='message',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
