# Generated by Django 4.2.6 on 2023-10-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='g1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='g2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='g3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentee',
            field=models.BooleanField(default=False),
        ),
    ]
