# Generated by Django 4.2.6 on 2023-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_g1_profile_g2_profile_g3_profile_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_mentee',
            field=models.BooleanField(default=False),
        ),
    ]
