# Generated by Django 4.2.6 on 2023-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_current_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chatid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
