# Generated by Django 4.2.6 on 2023-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
