# Generated by Django 4.2.6 on 2023-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_info_alter_grade_info_alter_lesson_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
