# Generated by Django 4.2.6 on 2023-10-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='num_topic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
