# Generated by Django 4.2.6 on 2023-10-10 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_lesson_num_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='in_progress',
            field=models.ManyToManyField(blank=True, related_name='in_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
