# Generated by Django 4.2.6 on 2023-10-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lessonstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstatus',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('done', 'Закончено')], default='in_progress', max_length=20),
        ),
    ]
