# Generated by Django 4.2.6 on 2023-10-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lessonstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='done',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='in_progress',
        ),
    ]
