# Generated by Django 4.2.6 on 2023-10-11 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_remove_lesson_done_remove_lesson_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='statuses',
            field=models.ManyToManyField(related_name='lessons', to='courses.lessonstatus'),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
