# Generated by Django 4.2.6 on 2023-10-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_lesson_statuses_lessonstatus_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstatus',
            name='lessons',
        ),
    ]
