# Generated by Django 4.2.6 on 2023-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_statustest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustest',
            name='lesson',
            field=models.ManyToManyField(to='courses.lesson'),
        ),
    ]
