# Generated by Django 4.2.6 on 2023-10-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_statustest_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusTest',
        ),
    ]
