# Generated by Django 4.2.6 on 2023-10-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_delete_statustest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('to_repeat', 'Повторить'), ('done', 'Закончено')], default='in_progress', max_length=20),
        ),
    ]
