# Generated by Django 4.2.6 on 2023-10-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lessonstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('to_repeat', 'Повторить'), ('done', 'Закончено')], default='not_started', max_length=20),
        ),
    ]
