# Generated by Django 4.2.6 on 2023-10-16 09:13

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lessonstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=markdownx.models.MarkdownxField(default=0),
            preserve_default=False,
        ),
    ]
