# Generated by Django 4.2.6 on 2023-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
