# Generated by Django 4.2.6 on 2023-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='info_hide',
            field=models.TextField(blank=True),
        ),
    ]
