# Generated by Django 4.2.6 on 2023-10-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_lesson_info_hide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['num_topic']},
        ),
    ]
