# Generated by Django 4.2.6 on 2023-10-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.grade'),
            preserve_default=False,
        ),
    ]
