# Generated by Django 4.2.6 on 2023-11-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_topic_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='grade',
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='num_lesson',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='num_topic',
            field=models.IntegerField(),
        ),
    ]
