# Generated by Django 4.2.6 on 2023-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_topic_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='num_topic',
            field=models.IntegerField(),
        ),
    ]
