# Generated by Django 4.2.6 on 2023-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_lesson_course_remove_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='on_top',
            field=models.BooleanField(default=False),
        ),
    ]
