# Generated by Django 4.2.6 on 2023-10-25 08:16

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_lesson_course_alter_lesson_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
