# Generated by Django 4.2.6 on 2023-10-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='num_lesson',
            field=models.IntegerField(),
        ),
    ]
