# Generated by Django 4.2.6 on 2023-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
