# Generated by Django 4.2.6 on 2023-10-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_lesson_num_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
