# Generated by Django 4.2.6 on 2023-10-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_topic_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='grade',
        ),
    ]
