# Generated by Django 4.2.6 on 2023-10-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_remove_lesson_course_remove_lesson_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
    ]
