# Generated by Django 4.2.6 on 2023-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='num_lesson',
            field=models.IntegerField(db_index=True),
        ),
    ]
